name: ci-build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew install --build-cache --scan -s
      - name: integration-test
        run: |
          export PATH=`pwd`/build/install/jbang/bin:$PATH
          cd src/test/resources
          ./test_suite.sh
  windows:
    runs-on: windows-latest
    steps:
      - name: test-gradle
          run: ./gradlew test --build-cache --scan -s
