name: ci-build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew build test install --build-cache --scan -s
      - name: integration-test
        if: {{ runner.os != 'Windows' }}
        run: |
          export PATH=`pwd`/build/install/jbang/bin:$PATH
          cd src/test/resources
          ./test_suite.sh
