on:
  push:
    tags:
      - 'v*'
name: release
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew build --build-cache --scan -s
      - name: tag-and-release
        env:
          ORG_GRADLE_PROJECT_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew githubRelease
      - name: homebrew
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: ./misc/updatebrew.sh
