on:
  release:
    types:
      - published

name: release-3rdparty
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew clean build install -x test --build-cache --scan -s
      - name: Download released sha256
          uses: Legion2/download-release-action@v2.1.0
          with:
            repository: maxandersen/jbang
            tag:  ${{ env.GITHUB_REF }}
            path: build/distributions
            file: jbang-${{ env.GITHUB_REF }}.zip.sha256
      - name: homebrew
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatebrew.sh
      - name: sdkman
        env:
          SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
        run: ./misc/updatesdkman.sh
