on:
  release:
    types:
      - published

name: release-3rdparty
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew clean build install -x test --build-cache --scan -s
      - name: homebrew
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatebrew.sh
      - name: sdkman
        env:
          SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
        run: ./misc/updatesdkman.sh
      - name: upload-choco
        uses: actions/upload-artifact@v1
        with:
          name: build-choco
          path: build/choco
  choco:
    runs-on: windows-latest
    name: publish-choco
    continue-on-error: true
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build-choco
          path: build/choco
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.204' # SDK Version to use.
      - name: choco-publish
        run: |
          choco pack build/choco/jbang.nuspec
          choco apikey -k ${{ secrets.CHOCO_API_KEY }} -source https://push.chocolatey.org/
          choco push jbang.*.nupkg -s https://push.chocolatey.org/

