on:
  release:
    types:
      - published

name: release-3rdparty
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew clean build install -x test --build-cache --scan -s
      - name: homebrew
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatebrew.sh
      - name: sdkman
        env:
          SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
        run: ./misc/updatesdkman.sh
      - name: choco-pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack build/choco/jbang.nuspec
      - name: choco-login
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: apikey -k ${{ secrets.CHOCO_API_KEY }} -source https://push.chocolatey.org/
      - name: choco-push
        uses: crazy-max/ghaction-chocolatey@v1
        continue-on-error: true
        with:
          args: push jbang.*.nupkg -s https://push.chocolatey.org/

