on:
  push:
    tags:
      - 'v*'
name: release
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: install-java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-gradle
        run: ./gradlew clean build install --build-cache --scan -s
      - name: integration-test
        run: |
          export PATH=`pwd`/build/install/jbang/bin:$PATH
          pastdir=`pwd`
          cd src/test/resources
          ./test_suite.sh
          cd $pastdir
      - name: tag-and-release
        env:
          ORG_GRADLE_PROJECT_github_token: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew githubRelease
      - name: homebrew
        env:
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          BREW_USER: ${{ secrets.BREW_USER }}
        run: ./misc/updatebrew.sh
      - name: sdkman
        env:
          SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
        run: ./misc/updatesdkman.sh
